#+TITLE: 面试题 17.25. Word Rectangle LCCI
#+DATE: 2020-09-28 21:29
#+LAST_MODIFIED: 2020-09-28 21:31
#+STARTUP: overview
#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t
#+EXPORT_FILE_NAME: 面试题-17.25-word-rectangle-lcci
#+HUGO_BASE_DIR:~/G/blog
#+HUGO_SECTION: leetcode
#+HUGO_CATEGORIES:leetcode
#+HUGO_TAGS: Leetcode Algorithms

* Solution

* [[https://leetcode.com/problems/word-rectangle-lcci/][面试题 17.25. Word Rectangle LCCI]]
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
Hard U:6 D:0 AC:46.8% F:1.0601460078
#+end_quote

Given a list of millions of words, design an algorithm to create the
largest possible rectangle of letters such that every row forms a word
(reading left to right) and every column forms a word (reading top to
bottom). The words need not be chosen consecutively from the list but
all rows must be the same length and all columns must be the same
height.

If there are more than one answer, return any one of them. A word can be
used more than once.

*Example 1:*

#+BEGIN_EXAMPLE
  Input: ["this", "real", "hard", "trh", "hea", "iar", "sld"]
  Output:
  [
     "this",
     "real",
     "hard"
  ]
#+END_EXAMPLE

*Example 2:*

#+BEGIN_EXAMPLE
  Input: ["aa"]
  Output: ["aa","aa"]
#+END_EXAMPLE

*Notes:*

- =words.length <= 1000=
- =words[i].length <= 100=
- It's guaranteed that all the words are randomly generated.
** Hints
1. 首先根据单词长度对字典进行分组，因为你知道每一列的长度必须相同，每一行的长度也必须相同。
2. 你能找到一个特定长宽的单词矩阵吗？如果尝试了所有的选项会怎样？
3. 当矩形看起来无效时，可以使用trie提前终止吗？
** Companies

* [[https://leetcode-cn.com/problems/word-rectangle-lcci/][面试题 17.25. 单词矩阵]]
:PROPERTIES:
:VISIBILITY: folded
:END:

#+begin_quote
Hard U:6 D:0 AC:46.8% F:1.0601460078
#+end_quote

给定一份单词的清单，设计一个算法，创建由字母组成的面积最大的矩形，其中每一行组成一个单词(自左向右)，每一列也组成一个单词(自上而下)。不要求这些单词在清单里连续出现，但要求所有行等长，所有列等高。

如果有多个面积最大的矩形，输出任意一个均可。一个单词可以重复使用。

*示例 1:*

#+BEGIN_EXAMPLE
  输入: ["this", "real", "hard", "trh", "hea", "iar", "sld"]
  输出:
  [
     "this",
     "real",
     "hard"
  ]
#+END_EXAMPLE

*示例 2:*

#+BEGIN_EXAMPLE
  输入: ["aa"]
  输出: ["aa","aa"]
#+END_EXAMPLE

*说明：*

- =words.length <= 1000=
- =words[i].length <= 100=
- 数据保证单词足够随机
** Hints
1. 首先根据单词长度对字典进行分组，因为你知道每一列的长度必须相同，每一行的长度也必须相同。
2. 你能找到一个特定长宽的单词矩阵吗？如果尝试了所有的选项会怎样？
3. 当矩形看起来无效时，可以使用trie提前终止吗？
** Companies

